### ISSUE TITLE
IRIS for Health  2023.1.2 - Exception in thread "main" java.io.IOException

### ISSUE THREAD

**Issue by djanknecht** [litesolutions/cachedb-import#3]
Using cachedb-import on IRIS for Health  2023.1.2 results in java.io.IOException: Unexpected status: OK
 
_\CacheQuality\cachedb-import>java -jar "C:\CacheQuality\cachedb-import\cachedb-import-0.7-beta.3.jar" listItems cfg=C:\CacheQuality\cachedb-import\db.properties outputDir=C:\CacheQuality\cachedb-import\output verbose=true
Exception in thread "main" java.io.IOException: Unexpected status: OK
        at es.litesolutions.cache.RESTRunner.request(RESTRunner.java:313)
        at es.litesolutions.cache.RESTRunner.get(RESTRunner.java:251)
        at es.litesolutions.cache.RESTRunner.listItems(RESTRunner.java:58)
        at es.litesolutions.cache.commands.ListItemsCommand.execute(ListItemsCommand.java:28)
        at es.litesolutions.cache.CacheImport.main(CacheImport.java:142)_

Result is
{"status":{"errors":[],"summary":""},"console":[],"result":{"content":[{"name":"%Api.Atelier.cls","cat":"CLS","ts":"2023-11-29 18:06:43.259","upd":true,"db":"IRISLIB","gen":false},

So RESTRunner has to be changed:

**status = resultObject.getAsJsonObject("result").get("status").getAsString();**

must be changed to 

 **status = resultObject.getAsJsonObject("status").getAsString();**

Then it works.

**Comment by daimor** [comment]
Could you check the latest 0.8 version 
https://github.com/litesolutions/cachedb-import/releases/tag/v0.8

**Comment by djanknecht** [comment]
Yes, this one works!

Thank you.
